language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.6_with_system_site_packages"
    - "3.6-dev_with_system_site_packages"
    - "3.7-dev_with_system_site_packages"

addons:
  apt:
    packages:
    - python3-dev
    - gstreamer1.0-plugins-base
    - python3-gi

install: "pip install numpy opencv-python"

script: python3 -m unittest discover -s tests
