language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

addons:
    apt:
        packages:
            - python3-dev
            - gstreamer1.0-plugins-base
            - python3-gi

before_install:
    - export PYTHONPATH=$(readlink -f virtualenv/lib/python*/site-packages)
    - echo $PYTHONPATH

install: "pip3 install numpy opencv-python vext.gi --prefix=virtualenv"

script: python3 -m unittest discover -s tests
