language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"

addons:
    apt:
        packages:
            - python3-dev
            - gstreamer1.0-plugins-base
            - python3-gi

install:
    - "pip3 install numpy opencv-python"
    - "ln -s /usr/lib/python3/dist-packages/gi virtualenv/lib/python*/site-packages/"

script: python3 -m unittest discover -s tests
