language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

addons:
  apt:
    packages:
    - python3-dev
    - gstreamer1.0-plugins-base
    - gnome-common

# Yes Ubuntu has a package but the one for trusty is out of date, so we have to build gi from source
# Instructions for building GObject are from http://www.linuxfromscratch.org/blfs/view/7.10/general/gobject-introspection.html
before_install:
    - wget http://ftp.gnome.org/pub/gnome/sources/gobject-introspection/1.48/gobject-introspection-1.48.0.tar.xz
    - tar xvf gobject-introspection-1.48.0.tar.xz
    - cd gobject-introspection-1.48.0
    - ./configure --prefix=/usr --disable-static
    - sudo make install
    - cd ../

install: "pip install numpy opencv-python git+https://git.gnome.org/browse/pygobject@3.22.0"

script: python3 -m unittest discover -s tests
