language: python
sudo: false

branches:
    only:
        - master

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

install:
    - sudo apt-get install python3-dev python3-numpy
    - sudo apt-get install gstreamer1.0-plugins-base python3-gi

before_script:
    - git clone https://github.com/Itseez/opencv.git
    - cd opencv
    - mkdir build
    - cd build
    - cmake ..
    - make -j4
    - sudo make -j4 install
    - cd ../..

script: python3 -m unittest discover -s tests
