language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

addons:
    apt:
        sources:
            - sourceline: "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse"
        packages:
            - python3-dev
            - gstreamer1.0-plugins-base
            - gnome-common
            - libgirepository1.0-dev/trusty-backports

install: "pip install numpy opencv-python git+https://git.gnome.org/browse/pygobject@3.22.0"

script: python3 -m unittest discover -s tests
