language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

addons:
    apt:
        packages:
            - python3-dev
            - gstreamer1.0-plugins-base
            - gnome-common


# Yes Ubuntu has a package but the one for trusty is out of date, so we have to build gi from source
# Instructions for building GObject are from http://www.linuxfromscratch.org/blfs/view/7.10/general/gobject-introspection.html

# It also happens that glib is out of date, so that has be build following the instructions at:
# http://www.linuxfromscratch.org/blfs/view/7.10/general/glib2.html

before_install:
    - wget http://ftp.gnome.org/pub/gnome/sources/glib/2.48/glib-2.48.2.tar.xz
    - tar xf glib-2.48.2.tar.xz
    - cd glib-2.48.2
    - ./configure --prefix=/usr/local --with-pcre=system
    - make -j2
    - sudo make install
    - cd ../
    - wget https://launchpad.net/ubuntu/+archive/primary/+files/gobject-introspection_1.46.0.orig.tar.xz
    - tar xf gobject-introspection_1.46.0.tar.xz
    - cd gobject-introspection_1.46.0
    - ./configure --prefix=/usr/local --disable-static
    - make -j2
    - sudo make install
    - cd ../

install: "pip install numpy opencv-python git+https://git.gnome.org/browse/pygobject@3.22.0"

script: python3 -m unittest discover -s tests
