language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

addons:
  apt:
    packages:
    - python3-dev
    - gstreamer1.0-plugins-base
    - python3-gi

install: "pip install numpy opencv-python git+https://git.gnome.org/browse/pygobject"

script: python3 -m unittest discover -s tests
