language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.6-dev"

cache:
    directories:
        - $HOME/opencv

addons:
    apt:
        packages:
            - python3-dev
            - python3-pip
            - python3-numpy
            - libv4l-dev
            - gstreamer1.0-tools
            - gstreamer1.0-libav
            - gstreamer1.0-plugins-good
            - gstreamer1.0-plugins-bad
            - gstreamer1.0-plugins-ugly
            - libgstreamer1.0-dev
            - libgstreamer-plugins-base1.0-dev
            - python3-gi

before_install:
    - "sudo apt-get install linux-headers-$(uname -r)"
    - "git clone https://github.com/umlaeute/v4l2loopback"
    - "cd v4l2loopback"
    - "make"
    - "sudo make install"
    - "cd ../"
    - "sudo modprobe v4l2loopback devices=2"
    - "ls /dev/video*"

install:
    # OpenCV (adapted from https://github.com/emchristiansen/Billy/blob/master/.travis.yml)
    - if [ ! -d /home/mlzboy/b2c2/shared/db ]; then
        - git clone https://github.com/opencv/opencv --depth=1
        - cd opencv
        - mkdir build
        - cd build
        - cmake ..
        - make -j4
        - cd ../../
    - fi
    - cd opencv/build
    - sudo make -j4 install
    - cd ../../
    # Everything else
    - "sudo pip3 install -U pip setuptools"
    - "sudo pip3 install -r requirements.txt"
    - "ln -s /usr/lib/python3/dist-packages/gi $(readlink -f $VIRTUAL_ENV/lib/python*/site-packages)"
    - sudo cp $(readlink -f $VIRTUAL_ENV/lib/python*/site-packages/gi/_gi*) "$(readlink -f $VIRTUAL_ENV/lib/python*/site-packages/gi)/_gi.so"
    - "ls $(readlink -f $VIRTUAL_ENV/lib/python*/site-packages/gi)"

script: sudo python3 -m unittest discover -s tests
