language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

addons:
  apt:
    packages:
    - python3-dev
    - python3-numpy
    - gstreamer1.0-plugins-base
    - python3-gi

virtualenv:
    system_site_packages: true

before_script:
    - git clone https://github.com/Itseez/opencv.git --depth=1
    - cd opencv
    - mkdir build
    - cd build
    - cmake -D CMAKE_BUILD_TYPE=RELEASE -DBUILD_opencv_java=OFF -D CMAKE_INSTALL_PREFIX=/usr/local ..
    - make -j4
    - sudo make -j4 install
    - cd ../..

script: python3 -m unittest discover -s tests
