language: python
dist: trusty
sudo: required

branches:
    only:
        - master

python:
    - "3.6"
    - "3.6-dev"
    - "3.7-dev"

addons:
  apt:
    packages:
    - python3-dev
    - gstreamer1.0-plugins-base
    - gnome-common

before_install:
    - git clone git://git.gnome.org/gobject-introspection
    - cd gobject-introspection
    - ./configure --prefix=/usr --disable-static
    - sudo make install
    - cd ../

install: "pip install numpy opencv-python git+https://git.gnome.org/browse/pygobject@3.22.0"

script: python3 -m unittest discover -s tests
