#! /bin/sh
# /etc/init.d/streaming

# Move this script to /etc/init.d/streaming.
# Then do:
# $ chmod 755 /etc/init.d/streaming
# $ update-rc.d streaming defaults

# Some things that run always
touch /var/lock/streaming

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script streaming "
    # Run files here
    python3 /home/pi/ImageProcessing2017-python/main.py 2>&1 > /dev/null
    ;;
  stop)
    echo "Stopping script streaming"
    killall python3
    ;;
  *)
    echo "Usage: /etc/init.d/streaming {start|stop}"
    exit 1
    ;;
esac

exit 0
